/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author luke
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Person person;
    public CreateJPanel(Person p) {
        initComponents();
        person = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblPersonDetails = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblMaritalStatus = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldAge = new javax.swing.JTextField();
        radioYes = new javax.swing.JRadioButton();
        radioNo = new javax.swing.JRadioButton();
        lblHomeAddress = new javax.swing.JLabel();
        lblLocalAddress = new javax.swing.JLabel();
        lblHomeResident = new javax.swing.JLabel();
        lblHomeUnit = new javax.swing.JLabel();
        lblHomeStreet = new javax.swing.JLabel();
        lblHomeCity = new javax.swing.JLabel();
        lblHomeZipCode = new javax.swing.JLabel();
        lblLocalResident = new javax.swing.JLabel();
        lblLocalUnit = new javax.swing.JLabel();
        lblLocalStreet = new javax.swing.JLabel();
        lblLocalCity = new javax.swing.JLabel();
        lblLocalZipCode = new javax.swing.JLabel();
        lblBankAccount = new javax.swing.JLabel();
        lblAccountHolder = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        lblRoutingNumber = new javax.swing.JLabel();
        lblCurrentBalance = new javax.swing.JLabel();
        fieldHomeResident = new javax.swing.JTextField();
        fieldHomeUnit = new javax.swing.JTextField();
        fieldHomeStreet = new javax.swing.JTextField();
        fieldHomeCity = new javax.swing.JTextField();
        fieldHomeZipCode = new javax.swing.JTextField();
        fieldLocalResident = new javax.swing.JTextField();
        fieldLocalUnit = new javax.swing.JTextField();
        fieldLocalStreet = new javax.swing.JTextField();
        fieldLocalCity = new javax.swing.JTextField();
        fieldLocalZipCode = new javax.swing.JTextField();
        fieldAccountHolder = new javax.swing.JTextField();
        fieldCurrentBalance = new javax.swing.JTextField();
        fieldAccountType = new javax.swing.JTextField();
        fieldBankName = new javax.swing.JTextField();
        fieldRoutingNumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setText("Create a Person Profile");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 290, 50));

        lblPersonDetails.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblPersonDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblPersonDetails.setText("Person Details");
        add(lblPersonDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, -1));

        lblFirstName.setText("First Name");
        add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lblLastName.setText("Last Name");
        add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        lblAge.setText("Age");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        lblMaritalStatus.setText("Marital Status");
        add(lblMaritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        fieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstNameActionPerformed(evt);
            }
        });
        add(fieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 80, -1));
        add(fieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 80, -1));
        add(fieldAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 80, -1));

        buttonGroup1.add(radioYes);
        radioYes.setText("Yes");
        radioYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioYesActionPerformed(evt);
            }
        });
        add(radioYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        buttonGroup1.add(radioNo);
        radioNo.setText("No");
        add(radioNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        lblHomeAddress.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblHomeAddress.setText("Home Address");
        add(lblHomeAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblLocalAddress.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblLocalAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblLocalAddress.setText("Local Address");
        add(lblLocalAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        lblHomeResident.setText("Resident");
        add(lblHomeResident, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        lblHomeUnit.setText("Unit");
        add(lblHomeUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        lblHomeStreet.setText("Street");
        add(lblHomeStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        lblHomeCity.setText("City");
        add(lblHomeCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        lblHomeZipCode.setText("Zip Code");
        add(lblHomeZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        lblLocalResident.setText("Resident");
        add(lblLocalResident, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        lblLocalUnit.setText("Unit");
        add(lblLocalUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        lblLocalStreet.setText("Street");
        add(lblLocalStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        lblLocalCity.setText("City");
        add(lblLocalCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        lblLocalZipCode.setText("Zip Code");
        add(lblLocalZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        lblBankAccount.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblBankAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblBankAccount.setText("Bank Account");
        add(lblBankAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        lblAccountHolder.setText("Account Holder");
        add(lblAccountHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        lblBankName.setText("Bank Name");
        add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        lblAccountType.setText("Account Type");
        add(lblAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        lblRoutingNumber.setText("Routing Number");
        add(lblRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, -1));

        lblCurrentBalance.setText("Current Balance");
        add(lblCurrentBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));
        add(fieldHomeResident, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 110, -1));
        add(fieldHomeUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 90, -1));
        add(fieldHomeStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 90, -1));
        add(fieldHomeCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 90, -1));
        add(fieldHomeZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 90, -1));
        add(fieldLocalResident, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 100, -1));

        fieldLocalUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLocalUnitActionPerformed(evt);
            }
        });
        add(fieldLocalUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 90, -1));
        add(fieldLocalStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 90, -1));
        add(fieldLocalCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 90, -1));
        add(fieldLocalZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 90, -1));
        add(fieldAccountHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 100, -1));
        add(fieldCurrentBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 90, -1));

        fieldAccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAccountTypeActionPerformed(evt);
            }
        });
        add(fieldAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 90, -1));
        add(fieldBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 90, -1));
        add(fieldRoutingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 90, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFirstNameActionPerformed

    private void fieldAccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAccountTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAccountTypeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String firstName = fieldFirstName.getText();
        String lastName = fieldLastName.getText();
        String age = fieldAge.getText();
        boolean isMarried = radioYes.isSelected();
        
        String homeResident = fieldHomeResident.getText();
        String homeStreet = fieldHomeStreet.getText();
        String homeUnit = fieldHomeUnit.getText();
        String homeCity = fieldHomeCity.getText();
        String homeZipCode = fieldHomeZipCode.getText();
        
        String localResident = fieldLocalResident.getText();
        String localStreet = fieldLocalStreet.getText();
        String localUnit = fieldLocalUnit.getText();
        String localCity = fieldLocalCity.getText();
        String localZipCode = fieldLocalZipCode.getText();
        
        String accountHolder = fieldAccountHolder.getText();
        String bankName = fieldBankName.getText();
        String accountType = fieldAccountType.getText();
        String routingNumber = fieldRoutingNumber.getText();
        String currentBalance = fieldCurrentBalance.getText();
        
        if (firstName.isEmpty() || lastName.isEmpty() || age.isEmpty()
                || homeResident.isEmpty() || homeStreet.isEmpty() || homeUnit.isEmpty()
                || homeCity.isEmpty() || homeZipCode.isEmpty()
                || localResident.isEmpty() || localStreet.isEmpty() || localUnit.isEmpty()
                || localCity.isEmpty() || localZipCode.isEmpty()
                || accountHolder.isEmpty() || bankName.isEmpty() || accountType.isEmpty()
                || routingNumber.isEmpty() || currentBalance.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please fill in all fields before saving.",
                    "Missing Information",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
        
        person.setFirstName(firstName);
        person.setLastName(lastName);
        person.setAge(Integer.parseInt(age));
        person.setIsMarried(isMarried);
        
        person.getHomeAddress().setPersonName(homeResident);
        person.getHomeAddress().setStreetAddress(homeStreet);
        person.getHomeAddress().setUnitNum(homeUnit);
        person.getHomeAddress().setCity(homeCity);
        person.getHomeAddress().setZipCode(Integer.parseInt(homeZipCode));
        
        person.getLocalAddress().setPersonName(localResident);
        person.getLocalAddress().setStreetAddress(localStreet);
        person.getLocalAddress().setUnitNum(localUnit);
        person.getLocalAddress().setCity(localCity);
        person.getLocalAddress().setZipCode(Integer.parseInt(localZipCode));

        person.getBankAccount().setPersonName(accountHolder);
        person.getBankAccount().setAccountType(accountType);
        person.getBankAccount().setBankName(bankName);
        person.getBankAccount().setRoutingNumber(Long.parseLong(routingNumber));
        person.getBankAccount().setBalance(Double.parseDouble(currentBalance));
        
    } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Age, Zip Codes, Routing Number, and Balance must be numeric.",
                    "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
            return;
    }
        
        JOptionPane.showMessageDialog(this, "Succesfully Saved", "Success", JOptionPane.INFORMATION_MESSAGE);

        fieldFirstName.setText("");
        fieldLastName.setText("");
        fieldAge.setText("");
        buttonGroup1.clearSelection();
        fieldHomeResident.setText("");
        fieldHomeUnit.setText("");
        fieldHomeStreet.setText("");
        fieldHomeCity.setText("");
        fieldHomeZipCode.setText("");
        fieldLocalResident.setText("");
        fieldLocalUnit.setText("");
        fieldLocalStreet.setText("");
        fieldLocalCity.setText("");
        fieldLocalZipCode.setText("");
        fieldAccountHolder.setText("");
        fieldCurrentBalance.setText("");
        fieldAccountType.setText("");
        fieldBankName.setText("");
        fieldRoutingNumber.setText("");
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void radioYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioYesActionPerformed

    private void fieldLocalUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLocalUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLocalUnitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fieldAccountHolder;
    private javax.swing.JTextField fieldAccountType;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldBankName;
    private javax.swing.JTextField fieldCurrentBalance;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldHomeCity;
    private javax.swing.JTextField fieldHomeResident;
    private javax.swing.JTextField fieldHomeStreet;
    private javax.swing.JTextField fieldHomeUnit;
    private javax.swing.JTextField fieldHomeZipCode;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldLocalCity;
    private javax.swing.JTextField fieldLocalResident;
    private javax.swing.JTextField fieldLocalStreet;
    private javax.swing.JTextField fieldLocalUnit;
    private javax.swing.JTextField fieldLocalZipCode;
    private javax.swing.JTextField fieldRoutingNumber;
    private javax.swing.JLabel lblAccountHolder;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBankAccount;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblCurrentBalance;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblHomeCity;
    private javax.swing.JLabel lblHomeResident;
    private javax.swing.JLabel lblHomeStreet;
    private javax.swing.JLabel lblHomeUnit;
    private javax.swing.JLabel lblHomeZipCode;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLocalAddress;
    private javax.swing.JLabel lblLocalCity;
    private javax.swing.JLabel lblLocalResident;
    private javax.swing.JLabel lblLocalStreet;
    private javax.swing.JLabel lblLocalUnit;
    private javax.swing.JLabel lblLocalZipCode;
    private javax.swing.JLabel lblMaritalStatus;
    private javax.swing.JLabel lblPersonDetails;
    private javax.swing.JLabel lblRoutingNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton radioNo;
    private javax.swing.JRadioButton radioYes;
    // End of variables declaration//GEN-END:variables
}
