/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Product;

/**
 *
 * @author luke
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Product product;
    public ViewJPanel(Product p) {
        initComponents();
        product = p;
        displayProduct();             
    }

    private void displayProduct(){
        fieldName.setText(product.getName());
        fieldDescription.setText(product.getDescription());
        fieldAvailNum.setText(product.getAvailNum());
        fieldPrice.setText(product.getPrice());
        
        fieldManuStreetName.setText(product.getManufactureAddress().getStreetName());
        fieldManuUnitNumber.setText(product.getManufactureAddress().getUnitNum());
        fieldManuCity.setText(product.getManufactureAddress().getCity());
        fieldManuZipCode.setText(product.getManufactureAddress().getZipcode());
        
        fieldShippingStreetName.setText(product.getShippingAddress().getStreetName());
        fieldShippingUnitNumber.setText(product.getShippingAddress().getUnitNum());
        fieldShippingCity.setText(product.getShippingAddress().getCity());
        fieldShippingZipCode.setText(product.getShippingAddress().getZipcode());
        
       
                
                
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblAvailNumber = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        fieldDescription = new javax.swing.JTextField();
        fieldAvailNum = new javax.swing.JTextField();
        fieldPrice = new javax.swing.JTextField();
        lblManufactureAddress = new javax.swing.JLabel();
        lblShippingAddress = new javax.swing.JLabel();
        lblManuStreetName = new javax.swing.JLabel();
        lblManuUnitNumber = new javax.swing.JLabel();
        lblManuCity = new javax.swing.JLabel();
        lblManuZipCode = new javax.swing.JLabel();
        fieldManuStreetName = new javax.swing.JTextField();
        fieldManuUnitNumber = new javax.swing.JTextField();
        fieldManuCity = new javax.swing.JTextField();
        fieldManuZipCode = new javax.swing.JTextField();
        lblShippingStreetName = new javax.swing.JLabel();
        lblUnitNumber = new javax.swing.JLabel();
        lblShippingCity = new javax.swing.JLabel();
        lblShippingZipCode = new javax.swing.JLabel();
        fieldShippingStreetName = new javax.swing.JTextField();
        fieldShippingUnitNumber = new javax.swing.JTextField();
        fieldShippingCity = new javax.swing.JTextField();
        fieldShippingZipCode = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle.setText("View a Product");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 220, 40));

        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        lblDescription.setText("desription");
        add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        lblAvailNumber.setText("availNumb");
        add(lblAvailNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        lblPrice.setText("price");
        add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });
        add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 120, -1));
        add(fieldDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 120, -1));

        fieldAvailNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAvailNumActionPerformed(evt);
            }
        });
        add(fieldAvailNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 120, -1));
        add(fieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 120, -1));

        lblManufactureAddress.setText("manufacture address");
        add(lblManufactureAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        lblShippingAddress.setText("shipping address");
        add(lblShippingAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        lblManuStreetName.setText("Street Name");
        add(lblManuStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        lblManuUnitNumber.setText("Unit Number");
        add(lblManuUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        lblManuCity.setText("City");
        add(lblManuCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        lblManuZipCode.setText("Zip Code");
        add(lblManuZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));
        add(fieldManuStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 80, -1));

        fieldManuUnitNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldManuUnitNumberActionPerformed(evt);
            }
        });
        add(fieldManuUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 80, -1));
        add(fieldManuCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 80, -1));

        fieldManuZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldManuZipCodeActionPerformed(evt);
            }
        });
        add(fieldManuZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 80, -1));

        lblShippingStreetName.setText("Street Name");
        add(lblShippingStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        lblUnitNumber.setText("Unit Number");
        add(lblUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        lblShippingCity.setText("City");
        add(lblShippingCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        lblShippingZipCode.setText("Zip Code");
        add(lblShippingZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));
        add(fieldShippingStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 80, -1));

        fieldShippingUnitNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShippingUnitNumberActionPerformed(evt);
            }
        });
        add(fieldShippingUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 80, -1));
        add(fieldShippingCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 80, -1));

        fieldShippingZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShippingZipCodeActionPerformed(evt);
            }
        });
        add(fieldShippingZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void fieldAvailNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAvailNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAvailNumActionPerformed

    private void fieldManuUnitNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldManuUnitNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldManuUnitNumberActionPerformed

    private void fieldManuZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldManuZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldManuZipCodeActionPerformed

    private void fieldShippingUnitNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShippingUnitNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShippingUnitNumberActionPerformed

    private void fieldShippingZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShippingZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShippingZipCodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldAvailNum;
    private javax.swing.JTextField fieldDescription;
    private javax.swing.JTextField fieldManuCity;
    private javax.swing.JTextField fieldManuStreetName;
    private javax.swing.JTextField fieldManuUnitNumber;
    private javax.swing.JTextField fieldManuZipCode;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JTextField fieldShippingCity;
    private javax.swing.JTextField fieldShippingStreetName;
    private javax.swing.JTextField fieldShippingUnitNumber;
    private javax.swing.JTextField fieldShippingZipCode;
    private javax.swing.JLabel lblAvailNumber;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblManuCity;
    private javax.swing.JLabel lblManuStreetName;
    private javax.swing.JLabel lblManuUnitNumber;
    private javax.swing.JLabel lblManuZipCode;
    private javax.swing.JLabel lblManufactureAddress;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblShippingAddress;
    private javax.swing.JLabel lblShippingCity;
    private javax.swing.JLabel lblShippingStreetName;
    private javax.swing.JLabel lblShippingZipCode;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUnitNumber;
    // End of variables declaration//GEN-END:variables
}
