/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author luke
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Product product;
    public CreateJPanel(Product p) {
        initComponents();
        product = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblAvailNumber = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        fieldDescription = new javax.swing.JTextField();
        fieldAvailNum = new javax.swing.JTextField();
        fieldPrice = new javax.swing.JTextField();
        lblManufactureAddress = new javax.swing.JLabel();
        lblShippingAddress = new javax.swing.JLabel();
        lblManuStreetName = new javax.swing.JLabel();
        lblManuUnitNumber = new javax.swing.JLabel();
        lblManuCity = new javax.swing.JLabel();
        lblManuZipCode = new javax.swing.JLabel();
        fieldManuStreetName = new javax.swing.JTextField();
        fieldManuUnitNumber = new javax.swing.JTextField();
        fieldManuCity = new javax.swing.JTextField();
        fieldManuZipCode = new javax.swing.JTextField();
        lblShippingStreetName = new javax.swing.JLabel();
        lblUnitNumber = new javax.swing.JLabel();
        lblShippingCity = new javax.swing.JLabel();
        lblShippingZipCode = new javax.swing.JLabel();
        fieldShippingStreetName = new javax.swing.JTextField();
        fieldShippingUnitNumber = new javax.swing.JTextField();
        fieldShippingCity = new javax.swing.JTextField();
        fieldShippingZipCode = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblTitle.setText("Create a Product");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 220, 40));

        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        lblDescription.setText("description");
        add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        lblAvailNumber.setText("availNum");
        add(lblAvailNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        lblPrice.setText("price");
        add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });
        add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 120, -1));
        add(fieldDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 120, -1));

        fieldAvailNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAvailNumActionPerformed(evt);
            }
        });
        add(fieldAvailNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 120, -1));
        add(fieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 120, -1));

        lblManufactureAddress.setText("manufacture address");
        add(lblManufactureAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        lblShippingAddress.setText("shipping address");
        add(lblShippingAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        lblManuStreetName.setText("Street Name");
        add(lblManuStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        lblManuUnitNumber.setText("Unit Number");
        add(lblManuUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        lblManuCity.setText("City");
        add(lblManuCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        lblManuZipCode.setText("Zip Code");
        add(lblManuZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));
        add(fieldManuStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 80, -1));

        fieldManuUnitNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldManuUnitNumberActionPerformed(evt);
            }
        });
        add(fieldManuUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 80, -1));
        add(fieldManuCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 80, -1));

        fieldManuZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldManuZipCodeActionPerformed(evt);
            }
        });
        add(fieldManuZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 80, -1));

        lblShippingStreetName.setText("Street Name");
        add(lblShippingStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        lblUnitNumber.setText("Unit Number");
        add(lblUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        lblShippingCity.setText("City");
        add(lblShippingCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        lblShippingZipCode.setText("Zip Code");
        add(lblShippingZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));
        add(fieldShippingStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 80, -1));

        fieldShippingUnitNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShippingUnitNumberActionPerformed(evt);
            }
        });
        add(fieldShippingUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 80, -1));
        add(fieldShippingCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 80, -1));

        fieldShippingZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShippingZipCodeActionPerformed(evt);
            }
        });
        add(fieldShippingZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 80, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldAvailNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAvailNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAvailNumActionPerformed

    private void fieldManuUnitNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldManuUnitNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldManuUnitNumberActionPerformed

    private void fieldManuZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldManuZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldManuZipCodeActionPerformed

    private void fieldShippingUnitNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShippingUnitNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShippingUnitNumberActionPerformed

    private void fieldShippingZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShippingZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShippingZipCodeActionPerformed

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        // step 1: collect information from user input
        String productName = fieldName.getText();
        String description = fieldDescription.getText();
        String availNum = fieldAvailNum.getText();
        String price = fieldPrice.getText();
        
        String manuStreet = fieldManuStreetName.getText();
        String manuUnit = fieldManuUnitNumber.getText();
        String manuCity = fieldManuCity.getText();
        String manuZipCode = fieldManuZipCode.getText();
        
        String shippingStreet = fieldShippingStreetName.getText();
        String shippingUnit = fieldShippingUnitNumber.getText();
        String shippingCity = fieldShippingCity.getText();
        String shippingZipCode = fieldShippingZipCode.getText();
        
        
        // step 2: code all those information into a product
        product.setName(productName);
        product.setDescription(description);
        product.setAvailNum(availNum);
        product.setPrice(price);
        
        product.getManufactureAddress().setStreetName(manuStreet);
        product.getManufactureAddress().setUnitNum(manuUnit);
        product.getManufactureAddress().setCity(manuCity);
        product.getManufactureAddress().setZipcode(manuZipCode);
        
        product.getShippingAddress().setStreetName(shippingStreet);
        product.getShippingAddress().setUnitNum(shippingUnit);
        product.getShippingAddress().setCity(shippingCity);
        product.getShippingAddress().setZipcode(shippingZipCode);
                
      
        // step 3: give a pop-up message
        JOptionPane.showMessageDialog(this, "Successfully Saved!", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        // step 4:clear all text from text field
        fieldName.setText("");
        fieldDescription.setText("");
        fieldAvailNum.setText("");
        fieldPrice.setText("");
        fieldManuStreetName.setText("");
        fieldManuUnitNumber.setText("");
        fieldManuCity.setText("");
        fieldManuZipCode.setText("");
        fieldShippingUnitNumber.setText("");
        fieldShippingCity.setText("");
        fieldShippingZipCode.setText("");
   
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAvailNum;
    private javax.swing.JTextField fieldDescription;
    private javax.swing.JTextField fieldManuCity;
    private javax.swing.JTextField fieldManuStreetName;
    private javax.swing.JTextField fieldManuUnitNumber;
    private javax.swing.JTextField fieldManuZipCode;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JTextField fieldShippingCity;
    private javax.swing.JTextField fieldShippingStreetName;
    private javax.swing.JTextField fieldShippingUnitNumber;
    private javax.swing.JTextField fieldShippingZipCode;
    private javax.swing.JLabel lblAvailNumber;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblManuCity;
    private javax.swing.JLabel lblManuStreetName;
    private javax.swing.JLabel lblManuUnitNumber;
    private javax.swing.JLabel lblManuZipCode;
    private javax.swing.JLabel lblManufactureAddress;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblShippingAddress;
    private javax.swing.JLabel lblShippingCity;
    private javax.swing.JLabel lblShippingStreetName;
    private javax.swing.JLabel lblShippingZipCode;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUnitNumber;
    // End of variables declaration//GEN-END:variables
}
