/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.Owner;
import model.Service;
import model.ServiceCatalog;
import model.Vehicle;
import model.VehicleDirectory;
import java.awt.CardLayout;
import ui.VehicleManager.ManagerWorkAreaJPanel;

/**
 *
 * @author luke
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private VehicleDirectory vehicleDirectory;
    private ServiceCatalog serviceCatalog;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        this.vehicleDirectory = new VehicleDirectory();
        this.serviceCatalog = new ServiceCatalog();
        generateDemoData();
}
        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        btnOpenWorkArea = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnOpenWorkArea.setText("Open Manager Work Area");
        btnOpenWorkArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenWorkAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnOpenWorkArea)
                .addContainerGap(413, Short.MAX_VALUE))
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnOpenWorkArea)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(topJPanel);

        javax.swing.GroupLayout userProcessContainerLayout = new javax.swing.GroupLayout(userProcessContainer);
        userProcessContainer.setLayout(userProcessContainerLayout);
        userProcessContainerLayout.setHorizontalGroup(
            userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        userProcessContainerLayout.setVerticalGroup(
            userProcessContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenWorkAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenWorkAreaActionPerformed
        // TODO add your handling code here:
        ManagerWorkAreaJPanel panel = new ManagerWorkAreaJPanel(userProcessContainer, vehicleDirectory, serviceCatalog);
        userProcessContainer.add("ManagerWorkAreaJPanel", panel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOpenWorkAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenWorkArea;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel topJPanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
private void generateDemoData() {
     Service newService1 = serviceCatalog.addNewService();
        newService1.setServiceID(1);
        newService1.setServiceType("Oil Change");
        newService1.setCost(49.99);
        newService1.setMechanicName("Mike Ross");
        newService1.setServiceDuration(0.5f);

        Service newService2 = serviceCatalog.addNewService();
        newService2.setServiceID(2);
        newService2.setServiceType("Car Wash");
        newService2.setCost(15.00);
        newService2.setMechanicName("Ana Diaz");
        newService2.setServiceDuration(0.75f);

        Service newService3 = serviceCatalog.addNewService();
        newService3.setServiceID(3);
        newService3.setServiceType("Brake Inspection");
        newService3.setCost(89.50);
        newService3.setMechanicName("Raj Patel");
        newService3.setServiceDuration(1.5f);

        Owner newOwner1 = new Owner();
        newOwner1.setOwnerID(101);
        newOwner1.setFirstName("John");
        newOwner1.setLastName("Smith");
        newOwner1.setServiceDate("2026-09-28");

        Vehicle newVehicle1 = vehicleDirectory.addNewVehicle();
        newVehicle1.setVehicleId(201);
        newVehicle1.setMake("Toyota");
        newVehicle1.setModel("Camry");
        newVehicle1.setYear((short) 2021);
        newVehicle1.setRegistrationNumber("RI-4821");
        newVehicle1.setOwner(newOwner1);
        newVehicle1.setServiceOpted(newService1);

        Owner newOwner2 = new Owner();
        newOwner2.setOwnerID(102);
        newOwner2.setFirstName("Priya");
        newOwner2.setLastName("Nair");
        newOwner2.setServiceDate("2026-09-29");

        Vehicle newVehicle2 = vehicleDirectory.addNewVehicle();
        newVehicle2.setVehicleId(202);
        newVehicle2.setMake("Toyota");
        newVehicle2.setModel("Camry");
        newVehicle2.setYear((short) 2019);
        newVehicle2.setRegistrationNumber("RI-7734");
        newVehicle2.setOwner(newOwner2);
        newVehicle2.setServiceOpted(newService2);

        Owner newOwner3 = new Owner();
        newOwner3.setOwnerID(103);
        newOwner3.setFirstName("Leo");
        newOwner3.setLastName("Kim");
        newOwner3.setServiceDate("2026-09-30");

        Vehicle newVehicle3 = vehicleDirectory.addNewVehicle();
        newVehicle3.setVehicleId(203);
        newVehicle3.setMake("Honda");
        newVehicle3.setModel("Civic");
        newVehicle3.setYear((short) 2022);
        newVehicle3.setRegistrationNumber("RI-1190");
        newVehicle3.setOwner(newOwner3);
        newVehicle3.setServiceOpted(newService3);

        Owner newOwner4 = new Owner();
        newOwner4.setOwnerID(104);
        newOwner4.setFirstName("Sara");
        newOwner4.setLastName("Lopez");
        newOwner4.setServiceDate("2026-10-01");

        Vehicle newVehicle4 = vehicleDirectory.addNewVehicle();
        newVehicle4.setVehicleId(204);
        newVehicle4.setMake("Ford");
        newVehicle4.setModel("Escape");
        newVehicle4.setYear((short) 2020);
        newVehicle4.setRegistrationNumber("RI-5562");
        newVehicle4.setOwner(newOwner4);
        newVehicle4.setServiceOpted(newService1);

        Owner newOwner5 = new Owner();
        newOwner5.setOwnerID(105);
        newOwner5.setFirstName("Tom");
        newOwner5.setLastName("Reed");
        newOwner5.setServiceDate("2026-10-02");

        Vehicle newVehicle5 = vehicleDirectory.addNewVehicle();
        newVehicle5.setVehicleId(205);
        newVehicle5.setMake("Honda");
        newVehicle5.setModel("Accord");
        newVehicle5.setYear((short) 2018);
        newVehicle5.setRegistrationNumber("RI-3307");
        newVehicle5.setOwner(newOwner5);
        newVehicle5.setServiceOpted(newService2);
    }
}