/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Service;



/**
 *
 * @author luke
 */
public class ManageServicesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageServicesPanel
     */
    Service service;
    public ManageServicesPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblServiceID = new javax.swing.JLabel();
        lblRegisterVehicle = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();
        lblMechanicName = new javax.swing.JLabel();
        txtServiceID = new javax.swing.JTextField();
        txtRegisterVehicle = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        txtMechanicName = new javax.swing.JTextField();
        lblDuration = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblServiceID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServiceID.setText("Service ID");
        add(lblServiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 50, 65, -1));

        lblRegisterVehicle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegisterVehicle.setText("Register Vehicle");
        add(lblRegisterVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 85, -1, -1));

        lblCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCost.setText("Cost");
        add(lblCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 120, -1, -1));

        lblMechanicName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMechanicName.setText("Mechanic Name");
        add(lblMechanicName, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 155, -1, -1));
        add(txtServiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 47, 273, -1));
        add(txtRegisterVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 82, 273, -1));
        add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 117, 273, -1));

        txtMechanicName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMechanicNameActionPerformed(evt);
            }
        });
        add(txtMechanicName, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 152, 273, -1));

        lblDuration.setText("Duration (hours)");
        add(lblDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 187, -1, -1));

        txtDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurationActionPerformed(evt);
            }
        });
        add(txtDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 187, 273, -1));

        btnAdd.setText("Add");
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 245, -1, -1));

        btnUpdate.setText("Update");
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 245, -1, -1));

        btnDelete.setText("Delete");
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 245, -1, -1));

        btnClear.setText("Clear");
        add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 245, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtMechanicNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMechanicNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMechanicNameActionPerformed

    private void txtDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblMechanicName;
    private javax.swing.JLabel lblRegisterVehicle;
    private javax.swing.JLabel lblServiceID;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtMechanicName;
    private javax.swing.JTextField txtRegisterVehicle;
    private javax.swing.JTextField txtServiceID;
    // End of variables declaration//GEN-END:variables
}
