/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VehicleManager;

/**
 *
 * @author luke
 */
public class ManageServicesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageServicesJPanel
     */
    public ManageServicesJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblServiceID = new javax.swing.JLabel();
        lblServiceType = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();
        lblMechanic = new javax.swing.JLabel();
        txtServiceID = new javax.swing.JTextField();
        txtServiceType = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        txtMechanic = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageServices = new javax.swing.JTable();
        lblDuration = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 37, -1, -1));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Services");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 209, -1));

        lblServiceID.setText("Service ID");
        add(lblServiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 85, -1));

        lblServiceType.setText("Service Type");
        add(lblServiceType, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 85, -1));

        lblCost.setText("Cost");
        add(lblCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 85, -1));

        lblMechanic.setText("Mechanic");
        add(lblMechanic, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 85, -1));
        add(txtServiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 191, -1));
        add(txtServiceType, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 191, -1));
        add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 191, -1));

        txtMechanic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMechanicActionPerformed(evt);
            }
        });
        add(txtMechanic, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 191, -1));

        btnAdd.setText("Add");
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, -1, -1));

        btnUpdate.setText("Update");
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, -1, -1));

        tblManageServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Service ID", "Service Type", "Cost", "Mechanic", "Duration"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageServices);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 670, 170));

        lblDuration.setText("Duration");
        add(lblDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));
        add(txtDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtMechanicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMechanicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMechanicActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblMechanic;
    private javax.swing.JLabel lblServiceID;
    private javax.swing.JLabel lblServiceType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblManageServices;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtMechanic;
    private javax.swing.JTextField txtServiceID;
    private javax.swing.JTextField txtServiceType;
    // End of variables declaration//GEN-END:variables
}
