/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VehicleManager;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.ServiceCatalog;
import model.VehicleDirectory;
/**
 *
 * @author luke
 */
public class ManagerWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    VehicleDirectory vehicleDirectory;
    ServiceCatalog serviceCatalog;

    /**
     * Creates new form AccountMngWorkAreaJPanel
     */
    public ManagerWorkAreaJPanel(JPanel container, VehicleDirectory directory, ServiceCatalog catalog) {
        initComponents();

        userProcessContainer = container;
        vehicleDirectory = directory;
        serviceCatalog = catalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageServices = new javax.swing.JButton();
        btnRegisterVehicle = new javax.swing.JButton();
        btnManageVehicles = new javax.swing.JButton();

        btnManageServices.setText("Manage Services");
        btnManageServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageServicesActionPerformed(evt);
            }
        });

        btnRegisterVehicle.setText("Register Vehicle");
        btnRegisterVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterVehicleActionPerformed(evt);
            }
        });

        btnManageVehicles.setText("Manage Vehicles");
        btnManageVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVehiclesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnManageVehicles)
                    .addComponent(btnManageServices, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegisterVehicle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(607, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnManageServices)
                .addGap(18, 18, 18)
                .addComponent(btnRegisterVehicle)
                .addGap(18, 18, 18)
                .addComponent(btnManageVehicles)
                .addContainerGap(615, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageServicesActionPerformed
        // TODO add your handling code here:
        ManageServicesJPanel panel = new ManageServicesJPanel(userProcessContainer, serviceCatalog);
        userProcessContainer.add("ManageServicesJPanel", panel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageServicesActionPerformed

    private void btnRegisterVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterVehicleActionPerformed
        // TODO add your handling code here:
        RegisterVehicleJPanel panel = new RegisterVehicleJPanel(userProcessContainer, vehicleDirectory, serviceCatalog);
        userProcessContainer.add("RegisterVehicleJPanel", panel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRegisterVehicleActionPerformed

    private void btnManageVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVehiclesActionPerformed
        // TODO add your handling code here:
        ManageVehiclesJPanel panel = new ManageVehiclesJPanel(userProcessContainer, vehicleDirectory, serviceCatalog);
        userProcessContainer.add("ManageVehiclesJPanel", panel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageVehiclesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageServices;
    private javax.swing.JButton btnManageVehicles;
    private javax.swing.JButton btnRegisterVehicle;
    // End of variables declaration//GEN-END:variables
}
