/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VehicleManager;

import javax.swing.JPanel;
import model.ServiceCatalog;
import model.VehicleDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import model.Owner;
import model.Service;
import model.Vehicle;

/**
 *
 * @author luke
 */
public class RegisterVehicleJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    VehicleDirectory vehicleDirectory;
    ServiceCatalog serviceCatalog;

    /**
     * Creates new form RegisterVehicleJPanel
     */
    public RegisterVehicleJPanel(JPanel container, VehicleDirectory directory, ServiceCatalog catalog) {
        initComponents();
        
        userProcessContainer = container;
        vehicleDirectory = directory;
        serviceCatalog = catalog;
        
        populateServiceComboBox();
    }
    
    private void populateServiceComboBox() {
    jComboBox1.removeAllItems();

    for (Service s : serviceCatalog.getServices()) {
        jComboBox1.addItem(s);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblServiceDate = new javax.swing.JLabel();
        lblOwnerID = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtOwnerID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtServiceDate = new javax.swing.JTextField();
        txtVehicleID = new javax.swing.JTextField();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtRegistrationNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblServiceDate.setText("Service Date");
        add(lblServiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 202, -1, -1));

        lblOwnerID.setText("Owner ID");
        add(lblOwnerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 92, -1, -1));

        lblLastName.setText("Last Name");
        add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 168, -1, -1));

        lblFirstName.setText("First Name");
        add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 127, -1, -1));

        jLabel5.setText("Make");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 329, -1, -1));

        jLabel6.setText("Vehicle ID");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 294, -1, -1));

        jLabel7.setText("Model");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 364, -1, -1));

        jLabel8.setText("Year");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 399, -1, -1));

        jLabel9.setText("Registration No.");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 428, -1, -1));

        jLabel10.setText("Service Opted");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel12.setText("Register Vehicles");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));
        add(txtOwnerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 89, 210, -1));
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 124, 210, -1));
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 165, 210, -1));

        txtServiceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceDateActionPerformed(evt);
            }
        });
        add(txtServiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 199, 210, -1));
        add(txtVehicleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 291, 210, -1));
        add(txtMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 326, 210, -1));
        add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 361, 210, -1));
        add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 396, 210, -1));
        add(txtRegistrationNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 210, -1));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setText("Owner");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel14.setText("Vehicle");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 210, -1));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtServiceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceDateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        int ownerID;
        int vehicleID;
        short year;

        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String serviceDate = txtServiceDate.getText();
        String make = txtMake.getText();
        String model = txtModel.getText();
        String registrationNo = txtRegistrationNo.getText();
        Service selectedService = (Service) jComboBox1.getSelectedItem();

        if (txtOwnerID.getText().isBlank() || firstName.isBlank() || lastName.isBlank() || serviceDate.isBlank()
                || txtVehicleID.getText().isBlank() || make.isBlank() || model.isBlank()
                || txtYear.getText().isBlank() || registrationNo.isBlank() || selectedService == null) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            ownerID = Integer.parseInt(txtOwnerID.getText());
            vehicleID = Integer.parseInt(txtVehicleID.getText());
            year = Short.parseShort(txtYear.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Owner ID, Vehicle ID and Year inputs.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Owner o = new Owner();
        o.setOwnerID(ownerID);
        o.setFirstName(firstName);
        o.setLastName(lastName);
        o.setServiceDate(serviceDate);

        Vehicle v = vehicleDirectory.addNewVehicle();
        v.setVehicleId(vehicleID);
        v.setMake(make);
        v.setModel(model);
        v.setYear(year);
        v.setRegistrationNumber(registrationNo);
        v.setOwner(o);
        v.setServiceOpted(selectedService);

        JOptionPane.showMessageDialog(this, "Vehicle successfully registered.", "Information", JOptionPane.INFORMATION_MESSAGE);

        txtOwnerID.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtServiceDate.setText("");
        txtVehicleID.setText("");
        txtMake.setText("");
        txtModel.setText("");
        txtYear.setText("");
        txtRegistrationNo.setText("");
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<Service> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblOwnerID;
    private javax.swing.JLabel lblServiceDate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOwnerID;
    private javax.swing.JTextField txtRegistrationNo;
    private javax.swing.JTextField txtServiceDate;
    private javax.swing.JTextField txtVehicleID;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
