/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VehicleManager;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Service;
import model.ServiceCatalog;
import model.Vehicle;
import model.VehicleDirectory;

/**
 *
 * @author luke
 */
public class ViewVehicleJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private VehicleDirectory vehicleDirectory;
    private ServiceCatalog serviceCatalog;
    private Vehicle vehicle;


    /**
     * Creates new form ViewVehicleJPanel
     */
    public ViewVehicleJPanel(JPanel userProcessContainer, VehicleDirectory directory, ServiceCatalog catalog, Vehicle vehicle) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.serviceCatalog = catalog;
        this.vehicle = vehicle;

        populateServiceComboBox();
        refreshTextFields();
        setViewMode();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblServiceDate = new javax.swing.JLabel();
        lblOwnerID = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtOwnerID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtServiceDate = new javax.swing.JTextField();
        txtVehicleID = new javax.swing.JTextField();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtMechanic = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblMechanic = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();
        txtRegistrationNo2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblServiceDate.setText("Service Date");
        add(lblServiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 202, -1, -1));

        lblOwnerID.setText("Owner ID");
        add(lblOwnerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 92, -1, -1));

        lblLastName.setText("Last Name");
        add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 168, -1, -1));

        lblFirstName.setText("FIrst Name");
        add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 127, -1, -1));

        jLabel5.setText("Make");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jLabel6.setText("Vehicle ID");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jLabel7.setText("Model");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jLabel8.setText("Year");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        jLabel9.setText("Registration No.");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        jLabel10.setText("Service Opted");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel12.setText("View Vehicles");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));
        add(txtOwnerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 89, 210, -1));
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 124, 210, -1));
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 165, 210, -1));

        txtServiceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceDateActionPerformed(evt);
            }
        });
        add(txtServiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 199, 210, -1));
        add(txtVehicleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 210, -1));
        add(txtMake, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 210, -1));
        add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 210, -1));
        add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 210, -1));
        add(txtMechanic, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 210, -1));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setText("Owner");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel14.setText("Vehicle");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 210, -1));

        lblMechanic.setText("Mechanic");
        add(lblMechanic, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, -1, -1));

        lblDuration.setText("Duration ");
        add(lblDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, -1, -1));
        add(txtDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 210, -1));
        add(txtRegistrationNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 210, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, -1, -1));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtServiceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceDateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] panelStack = userProcessContainer.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];
        ManageVehiclesJPanel manageVehiclesJPanel = (ManageVehiclesJPanel) lastPanel;
        manageVehiclesJPanel.populateTable();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);


    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         setEditMode();
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int ownerID;
        int vehicleID;
        short year;

        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String serviceDate = txtServiceDate.getText();
        String make = txtMake.getText();
        String model = txtModel.getText();
        String registrationNo = txtRegistrationNo2.getText();
        Service selectedService = (Service) jComboBox1.getSelectedItem();

        if (txtOwnerID.getText().isBlank() || firstName.isBlank() || lastName.isBlank() || serviceDate.isBlank()
                || txtVehicleID.getText().isBlank() || make.isBlank() || model.isBlank()
                || txtYear.getText().isBlank() || registrationNo.isBlank() || selectedService == null)
        {
            JOptionPane.showMessageDialog(null, "All fields are mandatory.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            ownerID = Integer.parseInt(txtOwnerID.getText().trim());
            vehicleID = Integer.parseInt(txtVehicleID.getText().trim());
            year = Short.parseShort(txtYear.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Owner ID, Vehicle ID and Year inputs.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        vehicle.getOwner().setOwnerID(ownerID);
        vehicle.getOwner().setFirstName(firstName);
        vehicle.getOwner().setLastName(lastName);
        vehicle.getOwner().setServiceDate(serviceDate);

        vehicle.setVehicleId(vehicleID);
        vehicle.setMake(make);
        vehicle.setModel(model);
        vehicle.setYear(year);
        vehicle.setRegistrationNumber(registrationNo);
        vehicle.setServiceOpted(selectedService);

        JOptionPane.showMessageDialog(null, "Vehicle successfully updated.", "Information", JOptionPane.INFORMATION_MESSAGE);

        refreshTextFields();
        setViewMode();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Service> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMechanic;
    private javax.swing.JLabel lblOwnerID;
    private javax.swing.JLabel lblServiceDate;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtMechanic;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOwnerID;
    private javax.swing.JTextField txtRegistrationNo2;
    private javax.swing.JTextField txtServiceDate;
    private javax.swing.JTextField txtVehicleID;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
 private void populateServiceComboBox() {
        jComboBox1.removeAllItems();
        for (Service s : serviceCatalog.getServices()) {
            jComboBox1.addItem(s);
        }
    }

    private void refreshTextFields() {
        txtOwnerID.setText(String.valueOf(vehicle.getOwner().getOwnerID()));
        txtFirstName.setText(vehicle.getOwner().getFirstName());
        txtLastName.setText(vehicle.getOwner().getLastName());
        txtServiceDate.setText(vehicle.getOwner().getServiceDate());
        txtVehicleID.setText(String.valueOf(vehicle.getVehicleId()));
        txtMake.setText(vehicle.getMake());
        txtModel.setText(vehicle.getModel());
        txtYear.setText(String.valueOf(vehicle.getYear()));
        txtRegistrationNo2.setText(vehicle.getRegistrationNumber());
        jComboBox1.setSelectedItem(vehicle.getServiceOpted());
        txtMechanic.setText(vehicle.getServiceOpted().getMechanicName());
        txtDuration.setText(String.valueOf(vehicle.getServiceOpted().getServiceDuration()));
    }

    private void setViewMode() {
        txtOwnerID.setEnabled(false);
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtServiceDate.setEnabled(false);
        txtVehicleID.setEnabled(false);
        txtMake.setEnabled(false);
        txtModel.setEnabled(false);
        txtYear.setEnabled(false);
        txtRegistrationNo2.setEnabled(false);
        jComboBox1.setEnabled(false);
        txtMechanic.setEnabled(false);
        txtDuration.setEnabled(false);
        jButton1.setEnabled(false);
        btnUpdate.setEnabled(true);
    }

    private void setEditMode() {
        txtOwnerID.setEnabled(true);
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtServiceDate.setEnabled(true);
        txtVehicleID.setEnabled(true);
        txtMake.setEnabled(true);
        txtModel.setEnabled(true);
        txtYear.setEnabled(true);
        txtRegistrationNo2.setEnabled(true);
        jComboBox1.setEnabled(true);
        txtMechanic.setEnabled(false);
        txtDuration.setEnabled(false);
        jButton1.setEnabled(true);
        btnUpdate.setEnabled(false);
    }
}
